#
###################################
# Site wide configuration
####################################
#
title: steven's blog
email: steven@greatfeatservices.com
description: A simple blog for my self.
url: https://stevenhwang.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Manila
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: steven
  avatar: avatar.png
  job: "DevOps"
  bio: "I want to live a simple life!"
  email: steven@greatfeatservices.com
  disqus-shortname: #username
  twitter: #username
  facebook: steven.hwang00
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: stevenhwang
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
