title: "I'm Steven"
title-font-size: '2em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

owner: Steven
email: steven@greatfeatservices.com
description: A simple blog for recording my life.
url: https://stevenhwang.github.io

permalink: :title/

# Build settings
timezone: Asia/Manila
markdown: kramdown
highlight: rouge
paginate: 8
paginate_path: /page:num/

# Comments
disqus-shortname: https-stevenhwang-github-io

# CSS
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
